# -*- coding: utf-8 -*-
"""quote_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0MmU3ySQ7G-z3V6cGKXya5nzGwBJsD5
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.goodreads.com/quotes'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

quote_elements = soup.find_all('div', class_='quote')

for quote_element in quote_elements:
    quote_text_element = quote_element.find(class_='quoteText')
    quote_author_element = quote_element.find(class_='authorOrTitle')

    if quote_text_element and quote_author_element:
        quote_text = quote_text_element.text.strip()
        quote_author = quote_author_element.text
        print("Quote:", quote_text)
        print("Author:", quote_author)
        print("--------------------")
    else:
        print("Quote or author element not found.")